name: CI/CD Pipeline

# 触发条件：
# - 当有 Pull Request 推送到 main 分支时，运行 CI 流程
# - 当代码合并到 main 分支时，运行 CI + CD 流程
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    name: Run Tests & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Run unit tests
        run: pytest tests/unit
      - name: Run flake8 lint
        run: flake8 src/ tests/

  cd:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rec-mlops:latest
      # 可选：触发 Prefect Flow
      # - name: Trigger Prefect Flow
      #   run: |
      #     curl -X POST <PREFECT_API_ENDPOINT> -H "Authorization: Bearer ${{ secrets.PREFECT_TOKEN }}"
      # 自动更新 k8s 部署文件（需自定义脚本）
      # - name: Update k8s deployment
      #   run: |
      #     python scripts/update_k8s_deployment.py --image ${{ secrets.DOCKERHUB_USERNAME }}/rec-mlops:latest
      #     kubectl apply -f k8s/
